name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "this is step 1"
      - name: step2
        run: echo "this is step 2"
